# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ustomer.proto\x12\x08\x63ustomer\"\x10\n\x02Id\x12\n\n\x02id\x18\x01 \x01(\x05\"P\n\x08\x43ustomer\x12\x18\n\x02id\x18\x01 \x01(\x0b\x32\x0c.customer.Id\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x12\n\x05\x65mail\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_email\"6\n\x0eListOfCustomer\x12$\n\x08\x63ustomer\x18\x01 \x03(\x0b\x32\x12.customer.Customer\"\x86\x01\n\x08Response\x12*\n\toperation\x18\x01 \x01(\x0e\x32\x17.customer.Response.Type\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x18\n\x10http_status_code\x18\x03 \x01(\x05\"&\n\x04Type\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x12\t\n\x05\x41LTER\x10\x02\"\x1a\n\x07Request\x12\x0f\n\x07request\x18\x01 \x01(\x05\x32\xa7\x02\n\x0c\x43ustomerList\x12@\n\x0fGetAllCustomers\x12\x11.customer.Request\x1a\x18.customer.ListOfCustomer\"\x00\x12\x31\n\x0bGetCustomer\x12\x0c.customer.Id\x1a\x12.customer.Customer\"\x00\x12\x37\n\x0b\x41\x64\x64\x43ustomer\x12\x12.customer.Customer\x1a\x12.customer.Response\"\x00\x12\x34\n\x0e\x44\x65leteCustomer\x12\x0c.customer.Id\x1a\x12.customer.Response\"\x00\x12\x33\n\rAlterCustomer\x12\x0c.customer.Id\x1a\x12.customer.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'customer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ID._serialized_start=28
  _ID._serialized_end=44
  _CUSTOMER._serialized_start=46
  _CUSTOMER._serialized_end=126
  _LISTOFCUSTOMER._serialized_start=128
  _LISTOFCUSTOMER._serialized_end=182
  _RESPONSE._serialized_start=185
  _RESPONSE._serialized_end=319
  _RESPONSE_TYPE._serialized_start=281
  _RESPONSE_TYPE._serialized_end=319
  _REQUEST._serialized_start=321
  _REQUEST._serialized_end=347
  _CUSTOMERLIST._serialized_start=350
  _CUSTOMERLIST._serialized_end=645
# @@protoc_insertion_point(module_scope)
